### ISSUE TITLE
Support SuperFreez (open source competitor to Greenify) same as Greenify. (Both O.S. apps available on F-droid)

### ISSUE THREAD

**Issue by famewolf** [rosenpin/always-on-amoled#2459]
Both Superfreez and Always On are available on F-Droid.org and it makes sense for two Open Source apps to cooperate so hopefully this will be useful to more than just me.

https://www.f-droid.org/en/packages/superfreeze.tool.android/

Also I know this is annoying but can you tell me how your app compares to "Always On Amoled Display" app which is also on F-droid.org? (https://f-droid.org/en/packages/com.tomer.alwayson and https://f-droid.org/en/packages/tomer.com.alwaysonamoledplugin which adds capacitive button support (does yours support that?)   I note their last version was back in 2016 so obviously yours is newer hopefully with more features?

Also is the pocket mode automatically enabled because I can't find anywhere in settings to enable/disable it.

Thank you for your time and this great app.  I'm using it on my Oneplus 7 Pro.

**Comment by rosenpin** [comment]
Both apps you linked are mine, it's the same app as in this repo./
Unfortunately I was unable to continue this app as open source so I stopped updating the repo. You can still get the app in the play store (in newer version, obviously)/
About greenify: support for this feature was dropped in Android o due to Android limitations, so there's no much point in adding support for another type of this app
